# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Check for WAV file
      run: |
        if [ ! -f ./Resources/VoicePlayer.wav ]; then
          echo "WAV file is missing!"
          exit 1
        fi
        echo "WAV file found."
    - name: Check for ASCII art file
      run: |
        if ! grep -q "Cyber Security" "./Program.cs"; then
          echo "ASCII art file is missing!"
          exit 1
        fi
        echo "ASCII art file found."
    - name: Check Code Formatting
      run: dotnet tool restore && dotnet format --check
